import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-white">
          <div>
            <Sidebar />
          </div>
          <div className="h-screen flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
